### ISSUE TITLE
Name of the module interfere with already installed modules

### ISSUE THREAD

**Issue by rnosal** [profitbricks/profitbricks-puppet#9]
After module installation:
`puppet module install profitbricks-puppet`
there is problem with other modules from puppetforge (https://forge.puppet.com/theforeman/puppet). Both of them have the same name which cause conflict:
> puppet 

Maybe the name should be changed to 
> profitbricks-puppet

**Comment by edevenport** [comment]
@rnosal We have released version 1.5.0 of the ProfitBricks module for Puppet. In addition to a number of changes, we renamed the module to "profitbricks-profitbricks" to match the module naming convention of [username]-[modulename]. This should avoid the naming conflict.
